package by.alex.task04.controller.command;

public enum CommandName {

    CHANGE_LOCALE,
    CHANGE_ACCOUNT_STATUS,
    FIND_ACCOUNT_BY_BALANCE,
    FIND_ACCOUNT_BY_NUMBER,
    SORT_ACCOUNT_BY_BALANCE_ASC,
    SORT_ACCOUNT_BY_BALANCE_DESC,
    CALCULATE_ACCOUNTS_BALANCE,
    CALCULATE_BLOCKED_ACCOUNT_BALANCE,
    CALCULATE_ACTIVE_ACCOUNT_BALANCE,
    NO_SUCH_COMMAND;

}
